In [4]:
import numpy as np
import torch

In [2]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


In [28]:
t= torch.FloatTensor([[[1.11,1.12,1.13,1.14,1.15],[1.21,1.22,1.23,1.24,1.25]],
                      
                      [[2.11,2.12,2.13,2.14,2.15],[2.21,2.22,2.23,2.24,2.25]],
                     
                     [[3.11,3.12,3.13,3.14,3.15],[3.21,3.22,3.23,3.24,3.25]]])
print(t)
print(t.shape)

tensor([[[1.1100, 1.1200, 1.1300, 1.1400, 1.1500],
         [1.2100, 1.2200, 1.2300, 1.2400, 1.2500]],

        [[2.1100, 2.1200, 2.1300, 2.1400, 2.1500],
         [2.2100, 2.2200, 2.2300, 2.2400, 2.2500]],

        [[3.1100, 3.1200, 3.1300, 3.1400, 3.1500],
         [3.2100, 3.2200, 3.2300, 3.2400, 3.2500]]])
torch.Size([3, 2, 5])


In [39]:
print(t.max())
print(t.max(dim=0))

tensor(3.2500)
(tensor([[3.1100, 3.1200, 3.1300, 3.1400, 3.1500],
        [3.2100, 3.2200, 3.2300, 3.2400, 3.2500]]), tensor([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]))


In [43]:
t = np.array([[[0,1,2],
             [3,4,5]],
              [[6,7,8],
              [9,10,11]]
             ])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [44]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [47]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [48]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [49]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [50]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [52]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [54]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [55]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [56]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [57]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [58]:
print(bt.long())

tensor([1, 0, 0, 1])


In [59]:
print(bt.float())

tensor([1., 0., 0., 1.])


In [60]:
x=torch.FloatTensor([[1,2], [3,4]])
y=torch.FloatTensor([[5,6], [7,8]])

In [62]:
print(torch.cat([x,y],dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [63]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,3])
z=torch.FloatTensor([5,6])
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 3.],
        [5., 6.]])


In [64]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [65]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [66]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [67]:
x=torch.FloatTensor([[1,2],[3,4]])

In [68]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [220]:
print(x.mul_(2.))
print(x)

tensor([[inf, inf],
        [inf, inf]])
tensor([[inf, inf],
        [inf, inf]])


In [6]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[4],[5]])
print(m1.matmul(m2))

tensor([[14.],
        [32.]])


In [8]:
 print(m1*m2) #크기가 다르면 broadcasting을 통해 크기를 맞추고 element-wise 곱셈을 진행

tensor([[ 4.,  8.],
        [15., 20.]])


In [9]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)
