In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
#항상 같은 결과가 나오도록 랜덤 시드 주기
torch.manual_seed(1)

In [5]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [6]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [9]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [10]:
b = torch.zeros(1,requires_grad = True)
print(b)

tensor([0.], requires_grad=True)


In [11]:
hypothesis = x_train*W+b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [12]:
cost = torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward1>)


In [18]:
optimizer = optim.SGD([W,b],lr=0.01)

In [21]:
nb_epochs = 2000
for epoch in range(nb_epochs +1):
    hypothesis = x_train*W+b
    cost = torch.mean((hypothesis-y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
                epoch,nb_epochs,W.item(),b.item(),cost.item()
        ))

Epoch    0/2000 W: 0.500, b: 0.214 Cost: 11.691541
Epoch  100/2000 W: 1.747, b: 0.575 Cost: 0.047709
Epoch  200/2000 W: 1.801, b: 0.452 Cost: 0.029481
Epoch  300/2000 W: 1.844, b: 0.356 Cost: 0.018218
Epoch  400/2000 W: 1.877, b: 0.279 Cost: 0.011257
Epoch  500/2000 W: 1.903, b: 0.220 Cost: 0.006956
Epoch  600/2000 W: 1.924, b: 0.173 Cost: 0.004299
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002656
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001641
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001014
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000627
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000387
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000239
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000148
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000091
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000056
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008