In [65]:
import numpy as np

In [66]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [67]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [68]:
b[:,1]

array([ 2,  6, 10])

In [69]:
b[-1]

array([ 9, 10, 11, 12])

In [70]:
b[-1,:]

array([ 9, 10, 11, 12])

In [71]:
b[-1,...]

array([ 9, 10, 11, 12])

In [72]:
b[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
xy = np.loadtxt('../data-01-test-score.csv', delimiter=',',dtype=np.float32)

In [74]:
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]

In [75]:
print(x_data.shape)
print(len(x_data))
print(x_data[:5])

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [76]:
print(y_data.shape)
print(len(y_data))
print(y_data[:5])

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [77]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [78]:
torch.manual_seed(1)

In [79]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
    def forward(self,x):
        return self.linear(x)

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), 1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction,y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))


Epoch    0/20 Cost: 28693.488281
Epoch    1/20 Cost: 10618.750000
Epoch    2/20 Cost: 3936.015137
Epoch    3/20 Cost: 1465.219604
Epoch    4/20 Cost: 551.693726
Epoch    5/20 Cost: 213.934631
Epoch    6/20 Cost: 89.052269
Epoch    7/20 Cost: 42.876003
Epoch    8/20 Cost: 25.799639
Epoch    9/20 Cost: 19.482420
Epoch   10/20 Cost: 17.143093
Epoch   11/20 Cost: 16.274509
Epoch   12/20 Cost: 15.949721
Epoch   13/20 Cost: 15.825986
Epoch   14/20 Cost: 15.776566
Epoch   15/20 Cost: 15.754660
Epoch   16/20 Cost: 15.742918
Epoch   17/20 Cost: 15.734917
Epoch   18/20 Cost: 15.728307
Epoch   19/20 Cost: 15.722219
Epoch   20/20 Cost: 15.716357


In [80]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [81]:
dataset = TensorDataset(x_train, y_train)

In [82]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [83]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [84]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        # print(batch_idx)
        # print(samples)
        x_train, y_train = samples

        prediction = model(x_train)

        cost = F.mse_loss(prediction,y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:6f}'.format(epoch,nb_epochs,batch_idx+1,len(dataloader),cost.item()))

Epoch    0/20 Batch 1/3 Cost: 46978.785156
Epoch    0/20 Batch 2/3 Cost: 6497.784668
Epoch    0/20 Batch 3/3 Cost: 5174.395996
Epoch    1/20 Batch 1/3 Cost: 711.106384
Epoch    1/20 Batch 2/3 Cost: 401.381378
Epoch    1/20 Batch 3/3 Cost: 212.294891
Epoch    2/20 Batch 1/3 Cost: 26.882061
Epoch    2/20 Batch 2/3 Cost: 0.057693
Epoch    2/20 Batch 3/3 Cost: 41.471272
Epoch    3/20 Batch 1/3 Cost: 13.444824
Epoch    3/20 Batch 2/3 Cost: 14.656877
Epoch    3/20 Batch 3/3 Cost: 5.495739
Epoch    4/20 Batch 1/3 Cost: 6.619390
Epoch    4/20 Batch 2/3 Cost: 19.459251
Epoch    4/20 Batch 3/3 Cost: 16.812302
Epoch    5/20 Batch 1/3 Cost: 19.544233
Epoch    5/20 Batch 2/3 Cost: 21.681740
Epoch    5/20 Batch 3/3 Cost: 13.138634
Epoch    6/20 Batch 1/3 Cost: 2.338879
Epoch    6/20 Batch 2/3 Cost: 21.505651
Epoch    6/20 Batch 3/3 Cost: 17.908745
Epoch    7/20 Batch 1/3 Cost: 8.261931
Epoch    7/20 Batch 2/3 Cost: 12.769864
Epoch    7/20 Batch 3/3 Cost: 24.187618
Epoch    8/20 Batch 1/3 Cost: 10.52

In [85]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[156.7833]], grad_fn=<AddmmBackward>)


In [86]:
import torch
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [88]:
class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]
    
    def __len__(self):
        return len(self.x_data)

    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data)
        y = torch.FloatTensor(self.y_data)
        return x,y

In [89]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [90]:
model = torch.nn.Linear(3,1)
optimizer = optim.SGD(model.parameters(), lr = 1e-5)

In [91]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples

        prediction = model(x_train)

        cost = F.mse_loss(prediction,y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 5605.632812
Epoch    0/20 Batch 2/3 Cost: 1758.405762
Epoch    0/20 Batch 3/3 Cost: 552.504150
Epoch    1/20 Batch 1/3 Cost: 174.517258
Epoch    1/20 Batch 2/3 Cost: 56.037830
Epoch    1/20 Batch 3/3 Cost: 18.900248
Epoch    2/20 Batch 1/3 Cost: 7.258955
Epoch    2/20 Batch 2/3 Cost: 3.609433
Epoch    2/20 Batch 3/3 Cost: 2.464880
Epoch    3/20 Batch 1/3 Cost: 2.105499
Epoch    3/20 Batch 2/3 Cost: 1.992240
Epoch    3/20 Batch 3/3 Cost: 1.956139
Epoch    4/20 Batch 1/3 Cost: 1.944193
Epoch    4/20 Batch 2/3 Cost: 1.939844
Epoch    4/20 Batch 3/3 Cost: 1.937863
Epoch    5/20 Batch 1/3 Cost: 1.936631
Epoch    5/20 Batch 2/3 Cost: 1.935619
Epoch    5/20 Batch 3/3 Cost: 1.934691
Epoch    6/20 Batch 1/3 Cost: 1.933805
Epoch    6/20 Batch 2/3 Cost: 1.932908
Epoch    6/20 Batch 3/3 Cost: 1.932013
Epoch    7/20 Batch 1/3 Cost: 1.931119
Epoch    7/20 Batch 2/3 Cost: 1.930222
Epoch    7/20 Batch 3/3 Cost: 1.929332
Epoch    8/20 Batch 1/3 Cost: 1.928447
Epoch    8/20

In [92]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.0180]], grad_fn=<AddmmBackward>)
