In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [5]:
torch.manual_seed(1)

In [6]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [7]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [8]:
W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [9]:
hypothesis = 1/ (1 + torch.exp(-(x_train.matmul(W)+b)))

In [10]:
print(hypothesis)
print(hypothesis.shape)
print(y_train)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [11]:
-(y_train[0] * torch.log(hypothesis[0]) + (1-y_train[0]) * torch.log(1 - hypothesis[0]))

tensor([0.6931], grad_fn=<NegBackward>)

In [12]:
losses = -(y_train * torch.log(hypothesis) + (1-y_train) * torch.log(1 - hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


In [13]:
cost = losses.mean()
print (cost)

tensor(0.6931, grad_fn=<MeanBackward1>)


In [14]:
F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [15]:
optimizer = optim.SGD([W,b], lr =1)

nb_epochs = 1000
for epoch in range(nb_epochs +1):

    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1-hypothesis)).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


In [16]:
hypothsis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)

tensor([[2.7711e-04],
        [3.1636e-02],
        [3.9014e-02],
        [9.5618e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)


In [17]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction)

tensor([[0],
        [0],
        [0],
        [1],
        [1],
        [1]], dtype=torch.uint8)


In [18]:
print(W)
print(b)

tensor([[3.2530],
        [1.5179]], requires_grad=True)
tensor([-14.4819], requires_grad=True)


In [19]:
optimizer = optim.SGD([W,b], lr =1)

nb_epochs = 1000
for epoch in range(nb_epochs +1):

    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost: 0.019834
Epoch  100/1000 Cost: 0.018149
Epoch  200/1000 Cost: 0.016730
Epoch  300/1000 Cost: 0.015517
Epoch  400/1000 Cost: 0.014469
Epoch  500/1000 Cost: 0.013554
Epoch  600/1000 Cost: 0.012748
Epoch  700/1000 Cost: 0.012033
Epoch  800/1000 Cost: 0.011394
Epoch  900/1000 Cost: 0.010819
Epoch 1000/1000 Cost: 0.010300


In [23]:
import numpy as np

xy = np.loadtxt('../data-03-diabetes.csv',delimiter=',',dtype=np.float32)
x_data=xy[:,0:-1]
y_data=xy[:,[-1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)


In [24]:
print(x_train[0:5])
print(y_train[0:5])

tensor([[-0.2941,  0.4874,  0.1803, -0.2929,  0.0000,  0.0015, -0.5312, -0.0333],
        [-0.8824, -0.1457,  0.0820, -0.4141,  0.0000, -0.2072, -0.7669, -0.6667],
        [-0.0588,  0.8392,  0.0492,  0.0000,  0.0000, -0.3055, -0.4927, -0.6333],
        [-0.8824, -0.1055,  0.0820, -0.5354, -0.7778, -0.1624, -0.9240,  0.0000],
        [ 0.0000,  0.3769, -0.3443, -0.2929, -0.6028,  0.2846,  0.8873, -0.6000]])
tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.]])


In [39]:
W = torch.zeros((8,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W,b],lr=1)

nb_epochs = 2000

for epoch in range(nb_epochs):
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 ==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch,nb_epochs,cost.item())) # @@: (1,) tensor,@@.item(): scalar value


Epoch    0/2000 Cost: 0.693147
Epoch  100/2000 Cost: 0.480661
Epoch  200/2000 Cost: 0.473846
Epoch  300/2000 Cost: 0.472511
Epoch  400/2000 Cost: 0.472051
Epoch  500/2000 Cost: 0.471851
Epoch  600/2000 Cost: 0.471758
Epoch  700/2000 Cost: 0.471713
Epoch  800/2000 Cost: 0.471692
Epoch  900/2000 Cost: 0.471681
Epoch 1000/2000 Cost: 0.471676
Epoch 1100/2000 Cost: 0.471673
Epoch 1200/2000 Cost: 0.471672
Epoch 1300/2000 Cost: 0.471671
Epoch 1400/2000 Cost: 0.471671
Epoch 1500/2000 Cost: 0.471671
Epoch 1600/2000 Cost: 0.471671
Epoch 1700/2000 Cost: 0.471670
Epoch 1800/2000 Cost: 0.471671
Epoch 1900/2000 Cost: 0.471671


In [40]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5])

tensor([[0],
        [1],
        [0],
        [1],
        [0]], dtype=torch.uint8)


In [41]:
print(prediction[:5])
print(y_train[:5])

tensor([[0],
        [1],
        [0],
        [1],
        [0]], dtype=torch.uint8)
tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.]])


In [42]:
correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

tensor([[1],
        [1],
        [1],
        [1],
        [1]], dtype=torch.uint8)


In [43]:
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('The model has an accuracy of {:2.2f}% for the train set.'.format(accuracy * 100))

The model has an accuracy of 76.94% for the train set.


In [45]:
model = nn.Sequential(nn.Linear(8,1),nn.Sigmoid())

In [47]:
optimizer = optim.SGD(model.parameters(),lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 ==0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch: {:4d}/{} Cost: {:.6f} Accuracy: {:2.2f}%.'.format(epoch,nb_epochs,cost.item(),accuracy))

Epoch:    0/1000 Cost: 0.633587 Accuracy: 0.67%.
Epoch:  100/1000 Cost: 0.479769 Accuracy: 0.77%.
Epoch:  200/1000 Cost: 0.473719 Accuracy: 0.77%.
Epoch:  300/1000 Cost: 0.472482 Accuracy: 0.77%.
Epoch:  400/1000 Cost: 0.472042 Accuracy: 0.77%.
Epoch:  500/1000 Cost: 0.471848 Accuracy: 0.77%.
Epoch:  600/1000 Cost: 0.471757 Accuracy: 0.77%.
Epoch:  700/1000 Cost: 0.471713 Accuracy: 0.77%.
Epoch:  800/1000 Cost: 0.471691 Accuracy: 0.77%.
Epoch:  900/1000 Cost: 0.471681 Accuracy: 0.77%.
Epoch: 1000/1000 Cost: 0.471676 Accuracy: 0.77%.


In [48]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(8,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,x):
        return self.sigmoid(self.linear(x))


In [51]:
model = BinaryClassifier()

optimizer = optim.SGD(model.parameters(),lr=1)

nb_epochs = 1000

for epoch in range(nb_epochs+1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/1000 Cost: 0.803927 Accuracy 34.52%
Epoch  100/1000 Cost: 0.480485 Accuracy 76.81%
Epoch  200/1000 Cost: 0.473825 Accuracy 77.21%
Epoch  300/1000 Cost: 0.472514 Accuracy 77.34%
Epoch  400/1000 Cost: 0.472055 Accuracy 77.08%
Epoch  500/1000 Cost: 0.471854 Accuracy 76.94%
Epoch  600/1000 Cost: 0.471760 Accuracy 76.81%
Epoch  700/1000 Cost: 0.471715 Accuracy 76.81%
Epoch  800/1000 Cost: 0.471692 Accuracy 76.94%
Epoch  900/1000 Cost: 0.471681 Accuracy 76.94%
Epoch 1000/1000 Cost: 0.471676 Accuracy 76.94%
